del C:\proyectos\java\tutorials\apache-kafka\target\pmd\pmdrequest.bin
del C:\proyectos\java\tutorials\core-groovy-modules\core-groovy\target\pmd\pmdrequest.bin
del C:\proyectos\java\tutorials\core-groovy-modules\core-groovy-2\target\pmd\pmdrequest.bin
del C:\proyectos\java\tutorials\core-groovy-modules\core-groovy-3\target\pmd\pmdrequest.bin
del C:\proyectos\java\tutorials\core-groovy-modules\core-groovy-collections\target\pmd\pmdrequest.bin
del C:\proyectos\java\tutorials\core-groovy-modules\core-groovy-strings\target\pmd\pmdrequest.bin
del C:\proyectos\java\tutorials\core-java-modules\core-java-22\target\pmd\pmdrequest.bin
del C:\proyectos\java\tutorials\core-java-modules\core-java-23\target\pmd\pmdrequest.bin
del C:\proyectos\java\tutorials\core-java-modules\core-java-concurrency-advanced-6\target\pmd\pmdrequest.bin
del C:\proyectos\java\tutorials\core-java-modules\core-java-concurrency-simple\target\pmd\pmdrequest.bin
del C:\proyectos\java\tutorials\core-java-modules\core-java-io-6\target\pmd\pmdrequest.bin
del C:\proyectos\java\tutorials\libraries-data-io\target\pmd\pmdrequest.bin
del C:\proyectos\java\tutorials\persistence-modules\spring-data-neo4j\target\pmd\pmdrequest.bin
del C:\proyectos\java\tutorials\persistence-modules\spring-persistence-simple\target\pmd\pmdrequest.bin
del C:\proyectos\java\tutorials\quarkus-modules\quarkus-vs-springboot\quarkus-project\target\pmd\pmdrequest.bin
del C:\proyectos\java\tutorials\spring-boot-modules\spring-boot-mvc-2\target\pmd\pmdrequest.bin
del C:\proyectos\java\tutorials\spring-di-2\target\pmd\pmdrequest.bin
del C:\proyectos\java\tutorials\spring-security-modules\spring-security-legacy-oidc\target\pmd\pmdrequest.bin
